- hosts: monitoring
  become: yes
  tasks:

  - name: Update and install Nginx
    apt:
      name: nginx
      state: present
      update_cache: yes

  - name: Install required packages for Docker
    ansible.builtin.package:
      name: "{{ item }}"
      state: present
    loop:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
    when: ansible_os_family == "Debian"

  - name: Install required packages for Docker (RHEL/CentOS)
    ansible.builtin.package:
      name: "{{ item }}"
      state: present
    loop:
      - yum-utils
      - device-mapper-persistent-data
      - lvm2
    when: ansible_os_family == "RedHat"

  - name: Add Docker GPG key
    ansible.builtin.shell: |
      curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
    args:
      warn: false

  - name: Add Docker repository
    ansible.builtin.shell: |
      add-apt-repository -y "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
    args:
      warn: false

  - name: Install Docker CE
    ansible.builtin.apt:
        name: docker-ce
        state: present
        update_cache: yes

  - name: Start and enable Docker service
    ansible.builtin.service:
      name: docker
      state: started
      enabled: yes

  - name: prometheus and grafana installation
    shell: |
      docker network create monitoring
      docker run -d --name prometheus --network monitoring -p 9090:9090 prom/prometheus
      docker run -d --name grafana --network monitoring -p 3000:3000 grafana/grafana
      docker network inspect monitoring
      docker logs prometheus
      docker logs grafana